services:
  spec-mesh:
    image: spec-mesh:latest
    container_name: spec-mesh
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./config.yml:/app/config.yml:ro
    restart: unless-stopped
    networks:
      - spec-mesh

networks:
  spec-mesh:
    driver: bridge
