sources:
  - name: test
    url: http://192.168.1.129:8001/
    schema: http://192.168.1.129:8001/openapi.json
    enabled: true

settings:
  title: Merged API
  description: Merged API description
  version: 1.0.0
  grouping: true
  proxy: true
