sources:
  - name: test
    url: http://localhost:8001/
    schema: http://localhost:8001/openapi.json
    enabled: true

settings:
  title: Merged API
  description: Merged API description
  version: 1.0.0
  grouping: true
  proxy: true
