[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"


[project]
name = "openapi_merger"
version = "0.1.0"
requires-python = ">=3.13"

[tool.maturin]
features = ["pyo3/extension-module"]
module-name = "openapi_merger"

[dependency-groups]
dev = ["maturin>=1.9.4"]
